//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocument
    {
        public int DocumentId { get; set; }
        public int ProjectId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
